### ISSUE TITLE
Assumption is made that extension is .schema.json

### ISSUE THREAD

**Issue by Relequestual** [adobe/jsonschema2md#110]
In a closed issue (https://github.com/adobe/jsonschema2md/issues/43) there's a link to a commit (https://github.com/robinvenneman/jsonschema2md/commit/3d25c37bee9adc987032ddd5903250eeab302a09#diff-2cce40143051e25f811b56c79d619bf5R36) which seems to have been merged.

I'm able to use argument `-e` to define my own extension ('json' in my case, as opposed to .schema.json)

It should be documented that the expectation is that schema files have .schema.json extension, and that this can be overriden using `-e`.

**Comment by jbouduin** [comment]
If I run `jsonschema2md` or `jsonschema2md --help`, I get following output:
![image](https://user-images.githubusercontent.com/44770683/100387746-1d66c980-3029-11eb-8050-0e4b01131c74.png)

For me, that's documented (is there any other docu?)

**Comment by Relequestual** [comment]
I'd expect to see this in the repo readme
