### ISSUE TITLE
Semantic Release failing / Changelog correction required?

### ISSUE THREAD

**Issue by Relequestual** [adobe/jsonschema2md#113]
Version 2.0.0 was released.
The changelog was automatically generated by semantic-release-bot.
Issue #67 was fixed by PR #90, but the PR (nor the merge commit) didn't use the require template for the semantic release bot to pick up on the change for the changelog.

Documented: [Semantic Release commit message format](https://github.com/semantic-release/semantic-release#commit-message-format)

Actions required to resolve:

- [ ] Fix the changelog to include #67 
- [ ] Resolve / close #67 
- [x] Consider using [commitlint](https://github.com/conventional-changelog/commitlint) in CI

I'm not sure how you go about fixing the changelog in this situation.
Possibly manually?

**Comment by Relequestual** [comment]
It looks like releases only happen if the commit format for semantic-release is used.
Look at the "publish release" section of https://circleci.com/gh/adobe/jsonschema2md/323 for example.

**Comment by trieloff** [comment]
I'd say #121 fixes this. As long as we use `npm run commit` we should be good. I can also add the `commitlint` bot, so that we will see it right in the PR.

**Comment by trieloff** [comment]
I've enabled the commitlint bot.

**Comment by Relequestual** [comment]
Super. I think that helps prevent it happening again.
Do you feel we need to fix the changelog or given it's an early change and just a fix, it's probably not worth fixing?

**Comment by trieloff** [comment]
I'd leave the changelog as is.
