### ISSUE TITLE
Fix heading formatting issues with kramdown

### ISSUE THREAD

**Issue by fmeschbe** [adobe/jsonschema2md#117]
## What did you do

Include generated markdown in GitHub pages which uses kramdown to convert markdown to HTML.

## What did you expect to happen

Proper rendering of tables and headings

## What happened

Tables and headings are not rendered as such but just common text. The reason for this is that kramdown seems to expect blank lines before heading lines to properly render them.

## What's your environment

* Operating System: macOS Mojave
* node.js version: 10.15.3

## Do you have example files:

n/a -- the issue is downstream with converting to HTML using kramdown

**Comment by Relequestual** [comment]
Hey @fmeschbe Can you give a specific example of where you see this please?
I can see this works in the example markdown in the repo itself. For example: https://github.com/adobe/jsonschema2md/blob/master/examples/docs/arrays.schema.md

**Comment by fmeschbe** [comment]
Thanks @anjankaur for merging.

At @Relequestual take for example [deepextending.schema.md line 16](https://github.com/adobe/jsonschema2md/blame/b8a3b07dbc3d5be7e65307062b0276cff3226c92/spec/examples/deepextending.schema.md#L16). Before it was like

    | Can be instantiated | Yes | Experimental | Yes | Forbidden | Permitted | [deepextending.schema.json](deepextending.schema.json) |
    ## Schema Hierarchy

This rendered just as plain text with cram down while GitHub code view rendered as expected. Adding the blank line ahead of the title allows for proper table and title rendering.

Similar for [line 94](https://github.com/adobe/jsonschema2md/blame/b8a3b07dbc3d5be7e65307062b0276cff3226c92/spec/examples/deepextending.schema.md#L94) in that same file:

    ## baz
    ### BAAAZ!

Without the blank line, the _BAAAZ!_ title is not rendered as a title but just as plain text.
