### ISSUE TITLE
How to include enum value comments?

### ISSUE THREAD

**Issue by generateui** [adobe/jsonschema2md#169]
in the [enum example](https://github.com/adobe/jsonschema2md/blob/master/examples/docs/enums.schema.md), I see a property typed to an enum. The enum documentation then shows a table per enum value. In this table, a "Description" column is present. This column is empty: 

https://imgur.com/a/0gxVDxt

What steps do I need to take to actually get comment values per enum value?

**Comment by trieloff** [comment]
You need the `meta:enum` property. Here is an example: https://github.com/adobe/xdm/blob/75771f79aaeed94c4a4b031c8937e50035695446/docs/reference/context/optinout.schema.md https://github.com/adobe/xdm/blob/75771f79aaeed94c4a4b031c8937e50035695446/docs/reference/context/optinout.schema.json
