### ISSUE TITLE
Nested Pattern Properties ignored

### ISSUE THREAD

**Issue by theindexer** [adobe/jsonschema2md#180]
Looking at the examples, specifically the following:
[nestedobj json](https://github.com/adobe/jsonschema2md/blob/master/examples/schemas/nestedobj.schema.json)
[nstedobj md](https://github.com/adobe/jsonschema2md/blob/master/examples/docs/nestedobj.schema.md)

I'd expect some sort of description of the patternProperties under "collaborators". Instead it's just silently ignored.

Is this expected/a misunderstanding on my part or a buggo?

**Comment by theindexer** [comment]
I got where I wanted to by adding some stuff to nested-properties/nested-property.ejs.

But I realized I was barking up the wrong tree and don't actually need this project so I'd say there's 0 stakeholders in this at the moment. Cool stuff though!

**Comment by trieloff** [comment]
Thanks for the update.
