### ISSUE TITLE
Markdown links with titles/tool tips break GitHub Pages

### ISSUE THREAD

**Issue by rjstelling** [adobe/jsonschema2md#189]
## What did you do

    jsonschema2md -d Schemas -o /Volumes/Projects/ProjectXXX-Documentation/serialised-line-item-format

## What did you expect to happen

All output is as expected, however link titles/tool tips are generated from an objects "description" causing GitHub Pages to generate links to the .md file instead of .html

## What happened

```markdown
-   [Address](./manifest-definitions-delivery-definitions-address.md) – `Address#/definitions/Delivery/definitions/Address`
-   [Colour](./manifest-definitions-leaf-definitions-layer-definitions-text-definitions-colour.md) – `Colour#/definitions/Leaf/definitions/Layer/definitions/Text/definitions/Colour`
-   [Delivery](./manifest-definitions-delivery.md) – `Delivery#/definitions/Delivery`
-   [Image](./manifest-definitions-leaf-definitions-layer-definitions-image.md) – `Image#/definitions/Leaf/definitions/Layer/definitions/Image`
-   [Layer](./manifest-definitions-leaf-definitions-layer.md) – `Layer#/definitions/Leaf/definitions/Layer`
-   [Leaf](./manifest-definitions-leaf.md "A Leaf describes the contained section of the product (i") – `Leaf#/definitions/Leaf`
-   [Order](./manifest-definitions-order.md "Order contains info about what and ahoy many of the products the user has created") – `Order#/definitions/Order`
-   [Postage](./manifest-definitions-delivery-definitions-postage.md) – `Postage#/definitions/Delivery/definitions/Postage`
-   [Text](./manifest-definitions-leaf-definitions-layer-definitions-text.md) – `Text#/definitions/Leaf/definitions/Layer/definitions/Text`
-   [Transform](./manifest-definitions-leaf-definitions-layer-definitions-image-definitions-transform.md "The Transform applied to an object") – `Transform#/definitions/Leaf/definitions/Layer/definitions/Image/definitions/Transform`
```

As you can see the `Leaf` link has a tool tip, this causes GitHub Pages to link to the .md file.

## What's your environment

* Operating System: macOS Catalina
* node.js version: v13.5.0

Is this a GitHub bug? Is there an option to disable link titles/tool tips?
![gh-bug](https://user-images.githubusercontent.com/207455/71734262-6dea9c80-2e43-11ea-87a8-57fbbfaff9bf.jpg)

**Comment by trieloff** [comment]
I'd assume that this is a GitHub bug, but the correct fix is probably a workaround in our code to remove the titles.

**Comment by trieloff** [comment]
It seems to be working here…

-   [Address](./manifest-definitions-delivery-definitions-address.md) – `Address#/definitions/Delivery/definitions/Address`
-   [Colour](./manifest-definitions-leaf-definitions-layer-definitions-text-definitions-colour.md) – `Colour#/definitions/Leaf/definitions/Layer/definitions/Text/definitions/Colour`
-   [Delivery](./manifest-definitions-delivery.md) – `Delivery#/definitions/Delivery`
-   [Image](./manifest-definitions-leaf-definitions-layer-definitions-image.md) – `Image#/definitions/Leaf/definitions/Layer/definitions/Image`
-   [Layer](./manifest-definitions-leaf-definitions-layer.md) – `Layer#/definitions/Leaf/definitions/Layer`
-   [Leaf](./manifest-definitions-leaf.md "A Leaf describes the contained section of the product (i") – `Leaf#/definitions/Leaf`
-   [Order](./manifest-definitions-order.md "Order contains info about what and ahoy many of the products the user has created") – `Order#/definitions/Order`
-   [Postage](./manifest-definitions-delivery-definitions-postage.md) – `Postage#/definitions/Delivery/definitions/Postage`
-   [Text](./manifest-definitions-leaf-definitions-layer-definitions-text.md) – `Text#/definitions/Leaf/definitions/Layer/definitions/Text`
-   [Transform](./manifest-definitions-leaf-definitions-layer-definitions-image-definitions-transform.md "The Transform applied to an object") – `Transform#/definitions/Leaf/definitions/Layer/definitions/Image/definitions/Transform`

**Comment by trieloff** [comment]
And it also works here: https://github.com/adobe/jsonschema2md/blob/fc362baae277f0e00417605c074ff38304928119/README.md

I'd say this is a GitHub Pages/Jekyll bug that should be fixed there.

**Comment by aloisklink** [comment]
Hi @rjstelling, I had this same issue.

In my case, it was an issue with the [jekyll-relative-links](https://rubygems.org/gems/jekyll-relative-links) library. My pull request fixing the issue has been merged already, https://github.com/benbalter/jekyll-relative-links/pull/60, but I'd expect it to take a while to get released, and then even longer until GitHub pages updates to use that version as well.

In the meantime, I had success in just specifying the latest version of jekyll-relative-links in my Gemfile, e.g.

```gemfile
gem "jekyll-relative-links", :git => "https://github.com/benbalter/jekyll-relative-links.git", :ref => "c00abd291eb161f9627724c9941d4937c47a9864"
```

Hope this helps!
