### ISSUE TITLE
Infinite loop in 4.0.3

### ISSUE THREAD

**Issue by trieloff** [adobe/jsonschema2md#194]
Thanks for your help.
But sorry, I still end up in an infinite loop with version `4.0.3`

_Originally posted by @AndyOGo in https://github.com/adobe/jsonschema2md/issues/185#issuecomment-572571131_

**Comment by AndyOGo** [comment]
Thanks @trieloff for opening another issue.

So far I have no reproduction available, I added one more test schema to my repo with a [self-referencing schema simply called `node.json`](https://github.com/axa-ch/cyclic-schemas-test/blob/master/schemas/node.json).
But it works all fine, I committed the result too:
https://github.com/axa-ch/cyclic-schemas-test/tree/master/docs

I need to search our repo further, hope I can distill a reproduction soon...

**Comment by trieloff** [comment]
Thanks Andy, as soon as you can reliably reproduce the issue I can start debugging.

**Comment by AndyOGo** [comment]
@trieloff I found a public repo of ours, which is failing, below is my PR with an install of `4.0.3`:
https://github.com/axa-ch/json-logic-js/pull/19

All schemas are here:
https://github.com/axa-ch/json-logic-js/tree/master/schemas

**Comment by AndyOGo** [comment]
Thanks for handling it so quickly 👍 
Works like a charm now 😄

**Comment by trieloff** [comment]
I ran into the same issue in my projects, so that was an additional motivation.
