### ISSUE TITLE
Header option seems to not be functional

### ISSUE THREAD

**Issue by lisastaehli** [adobe/jsonschema2md#209]
## What did you do
I tried to remove headers as described in #154 and #153.

## What did you expect to happen
That headers will be removed in the generated markdown files.

## What happened
The headers were not removed in the generated markdown files. I might be missing some parameters in the schema or the arguments but cannot seem to find the cause of this.

From my understanding, this part of the markdown below should be removed if this is working properly:

---- HEADER -----
# Branches Schema

```txt
undefined
```

Example.

| Abstract            | Extensible | Status         | Identifiable | Custom Properties | Additional Properties | Access Restrictions | Defined In                                                         |
| :------------------ | ---------- | -------------- | ------------ | :---------------- | --------------------- | ------------------- | ------------------------------------------------------------------ |
| Can be instantiated | No         | Unknown status | No           | Forbidden         | Allowed               | none                | [branches.json](..\..\..\out\branches.json "open original schema") |

---- HEADER -----

## What's your environment

* Operating System: Windows
* node.js version: v12.13.0

## Do you have example files:

For this schema
```json
{ 
   "type":"object",
   "title":"Branches",
   "description":"Example.",
   "required":[ 
      "BranchName",
      "BranchOrder",
      "Existing",
      "OwnerName",
      "UrbanEventID"
   ],
   "properties":{ 
      "GlobalID":{ 
         "type":[ 
            "string",
            "null"
         ],
         "description":"Global ID."
      },
      "CreationDate":{ 
         "type":"integer",
         "date":true
      }
   }
}
```

I'm getting following Markdown when running 
`jsonschema2md -d docs -o docs/md -h false`

# Branches Schema

```txt
undefined
```

Example.

| Abstract            | Extensible | Status         | Identifiable | Custom Properties | Additional Properties | Access Restrictions | Defined In                                                         |
| :------------------ | ---------- | -------------- | ------------ | :---------------- | --------------------- | ------------------- | ------------------------------------------------------------------ |
| Can be instantiated | No         | Unknown status | No           | Forbidden         | Allowed               | none                | [branches.json](..\..\..\out\branches.json "open original schema") |

## Branches Type

`object` ([Branches](branches.md))

# Branches Properties

| Property                      | Type      | Required | Nullable       | Defined by                                                                           |
| :---------------------------- | --------- | -------- | -------------- | :----------------------------------------------------------------------------------- |
| [GlobalID](#GlobalID)         | `string`  | Optional | can be null    | [Branches](branches-properties-globalid.md "undefined#/properties/GlobalID")         |
| [CreationDate](#CreationDate) | `integer` | Optional | cannot be null | [Branches](branches-properties-creationdate.md "undefined#/properties/CreationDate") |

## GlobalID

Global ID.

`GlobalID`

-   is optional
-   Type: `string`
-   can be null
-   defined in: [Branches](branches-properties-globalid.md "undefined#/properties/GlobalID")

### GlobalID Type

`string`

## CreationDate

`CreationDate`

-   is optional
-   Type: `integer`
-   cannot be null
-   defined in: [Branches](branches-properties-creationdate.md "undefined#/properties/CreationDate")

### CreationDate Type

`integer`

Thanks for the help!

**Comment by trieloff** [comment]
Yes, that looks like a bug.
