### ISSUE TITLE
Req: Relocate definitons.

### ISSUE THREAD

**Issue by KyleTryon** [adobe/jsonschema2md#226]
## What did you do

Construct a schema using multiple definitions in order to clean up the level of nesting in the final schema.

Generate documentation and view the top-level schema.

All of the definition groups appear at the top, above the properties which I would believe to be the main information a user would be looking for.

## What did you expect to happen

Definition files could be separate files, when users get to the area that would reference a definition, they could be linked to that reference file.

Alternatively maybe this could just be relocated to the bottom?

---

**Comment by trieloff** [comment]
Moving it to the bottom sounds reasonable.

**Comment by alainlecluse** [comment]
@trieloff  I think this issue can be closed
