### ISSUE TITLE
show .md instead of .html

### ISSUE THREAD

**Issue by shahzebsiddiqui** [adobe/jsonschema2md#245]
## What did you do

Hello my schemadocs are located in https://buildtesters.github.io/schemas/schemadocs/ this is part of a workflow that automates documentation creation of schema using this file https://github.com/buildtesters/schemas/blob/master/.github/workflows/jsonschemadocs.yml. Basically it pushes my schemadocs into `gh-pages` branch.

What i dont understand is why the some of the schemas are showing in `.md` and others in `.html`. I would want them to be in html https://buildtesters.github.io/schemas/schemadocs/#top-level-schemas

for instance the compiler schema is showing as  https://buildtesters.github.io/schemas/schemadocs/compiler-v1.md but there is a html page https://buildtesters.github.io/schemas/schemadocs/compiler-v1.html but it doesn't show up on click.

This however is not true if you click the `buildtest configuration schema ` link this shows up as https://buildtesters.github.io/schemas/schemadocs/settings.html even though there is a .md page.

It's as if all version schemas are not showing up properly. This is true with `script-v1.0` and `python-v1.0`. What is the reason behind this behavior. Can this be fixed?

**Comment by trieloff** [comment]
Hi. jsonschema2md only generates MD files, and it sounds like your problem lies either in the markdown to html step or with github pages.

**Comment by shahzebsiddiqui** [comment]
so can you look at https://github.com/buildtesters/schemas/tree/gh-pages/schemadocs this is the top-level location where schemadocs are generated into `gh-pages`. The found that clicking on the top-level schema: compiler, script, global showing the .md page and this doesn't look good. But i can change the url to html. The only one that shows html is the settings schema which is this markdown  https://raw.githubusercontent.com/buildtesters/schemas/gh-pages/schemadocs/settings.md i dont understand this.

**Comment by trieloff** [comment]
All internal links jsonschema2md generates are to MD files.

**Comment by shahzebsiddiqui** [comment]
thanks for the clarification. closing this issue
