### ISSUE TITLE
CLI does not grab designated schema

### ISSUE THREAD

**Issue by JSaaS** [adobe/jsonschema2md#257]
## What did you do
Calling from Command Line:
jsonschema2md -d standalone/schemas/Product.schema.json -o standalone/schemas/docs

## What did you expect to happen
That the Product.schema.json file should be processed and MarkDown files created for this schema to be created in the 'docs'-folder

## What happened
Error message: Input file "standalone/schemas/product.schemas.json" is not a directory!

## What's your environment

* Operating System: Windows 10
* node.js version: v12.16.3

## Do you have example files:

No, sorry. Not able to share these files and it shouldn't be needed since it is not processing at all?

**Comment by trieloff** [comment]
Try:

```bash
$ jsonschema2md -d standalone/schemas/ -o standalone/schemas/docs
```

**Comment by JSaaS** [comment]
Yep, that works. But, it then grabs ALL the schemas in the folder. I understood the documentation as it should be able to pinpoint a single schema file:

"path to directory containing all JSON Schemas or a single JSON Schema file. This will be considered as the baseURL. By default only files ending in .schema.json will be processed, unless the schema-extension is set with the -e flag."

**Comment by trieloff** [comment]
No, single file input does not work anymore.

**Comment by JSaaS** [comment]
Gah! Okey, the documentation of the arguments needs to be updated so it does not mislead anyone.

Thanks!
