### ISSUE TITLE
The page of a property named "properties" won't be rendered

### ISSUE THREAD

**Issue by ZeroAurora** [adobe/jsonschema2md#282]
### Expected Behaviour
The page should be rendered.

### Actual Behaviour
Not rendered, but the cli didn't raise an exception and the output pages contain links to the unrendered page.

#### Steps to Reproduce
1. Create `example.schema.json` with the following:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "properties": {
      "title": "won't be rendered",
      "type": "object",
      "properties": {
        "something": {
          "title": "can be rendered"
        }
      }
    }
  }
}
```
2. Run the tool.
3. Check `out`. It does not contain `example-properties-properties.md`, but contains  `example-properties-properties-properties-something.md`. Besides, `example.md` contains a link to `example-properties-properties.md`.

#### Platform and Version
Windows 10 with WSL2 (Debian Testing)
Node.js v12.20.1
@adobe/jsonschema2md 5.0.2

#### Logs taken while reproducing problem
No special outputs so not including.

~~btw why I am doing such a silly work lolol~~ But actually it's a serious thing

**Comment by trieloff** [comment]
Can you reproduce the same issue with 5.0.0?

**Comment by ZeroAurora** [comment]
> 
> 
> Can you reproduce the same issue with 5.0.0?

Yes

**Comment by puradawid** [comment]
Same problem here. I can't generate anything that has `properties` property. I can rename it and then it works fine, but it's not the workaround I can do.

**Comment by puradawid** [comment]
I think I found the reason of it:

There is a list of properties that won't be traversed, hence they won't be added to `loadedschemas` array:

https://github.com/adobe/jsonschema2md/blob/main/lib/traverseSchema.js#L17

```
function isSkippableKeyword(schema) {
  const skippableKeywords = ['examples', 'required', 'properties'];
  const containsCurrentSchema = contains((keyword) => eq(keyword, schema[pointer].split('/').pop()));

  return containsCurrentSchema(skippableKeywords);
}
```

Based on that:
- the code skips current node (`schema`), when its path ends with any of `['example', 'required', 'properties']`
- it doesn't change whether it's actual node underneath the proper properties

We easily can consider such schema:

```
"properties": {
  "type": "object",
  "properties": {
     "require": {
       "type": "object",
       "properties": {
       // ... and so on and so forth
       }
    }
  }
}
```
I can't figure out any condition that will be proper check for actual `property` case but not necessarily built on just name. Maybe the node's parent should have defined type of `object`? I can imagine such cases anyway...

**Comment by puradawid** [comment]
I have proposed a fix for it - that does consider whether the `properties` can be skipped only if the parent is really the object/array type - otherwise, they are not part of the meta-schema, therefore should not be skipped at all.
