### ISSUE TITLE
oneOf rules are not being generated correctly

### ISSUE THREAD

**Issue by juliofalbo** [adobe/jsonschema2md#297]
Hi.

I have a JSON schema where based on a value of one field, I'm doing some requirement validations in other fields (inside a nested object) but when I'm generating the MD, those rules are not being printed, only the "object" (in my case "legal")

## Json Schema

```json
{
  "$id": "https://julio.com/schemas/players/create",
  "type": "object",
  "required": [
    "players"
  ],
  "title": "Player Creation",
  "description": "This is a JSON schema",
  "properties": {
    "players": {
      "type": "array",
      "title": "players",
      "description": "All players to be created",
      "items": {
        "title": "Player",
        "type": "object",
        "required": [
          "name",
          "country",
          "legal"
        ],
        "properties": {
          "name": {
            "type": "string",
            "title": "Name",
            "description": "name",
            "examples": [
              "Julio"
            ],
            "testProperty": "Julio",
            "minLength": 1,
            "maxLength": 40
          },
          "country": {
            "type": "string",
            "title": "Country",
            "description": "Country selected",
            "examples": [
              "PT"
            ],
            "testProperty": "PT",
            "enum": [
              "AU",
              "BR",
              "IN",
              "NO",
              "PT"
            ]
          },
          "legal": {
            "type": "object",
            "title": "Legal",
            "description": "Legal Info of the Player",
            "properties": {
              "field1": {
                "type": "string",
                "title": "field1",
                "description": "field1",
                "examples": [
                  "ABC12347"
                ],
                "testProperty": "ABC12347",
                "minLength": 1,
                "maxLength": 40
              },
              "field2": {
                "type": "string",
                "title": "field2",
                "description": "field2",
                "examples": [
                  "aaaaa"
                ],
                "testProperty": "aaaaa",
                "minLength": 1,
                "maxLength": 20
              },
              "field3": {
                "type": "string",
                "title": "field3",
                "description": "field3",
                "examples": [
                  "001"
                ],
                "testProperty": "001",
                "minLength": 1,
                "maxLength": 3
              }
            }
          }
        },
        "oneOf": [
          {
            "title": "Brazil",
            "type": "object",
            "properties": {
              "country": {
                "examples": [
                  "BR"
                ],
                "testProperty": "BR",
                "enum": [
                  "BR"
                ]
              },
              "legal": {
                "required": [
                  "field1",
                  "field2",
                  "field3"
                ]
              }
            }
          },
          {
            "title": "India",
            "type": "object",
            "properties": {
              "country": {
                "examples": [
                  "IN"
                ],
                "testProperty": "IN",
                "enum": [
                  "IN"
                ]
              },
              "legal": {
                "required": [
                  "field1",
                  "field2"
                ]
              }
            }
          },
          {
            "title": "Other countries",
            "type": "object",
            "properties": {
              "country": {
                "examples": [
                  "AU"
                ],
                "testProperty": "AU",
                "enum": [
                  "PT",
                  "AU",
                  "NO"
                ]
              },
              "legal": {
                "required": [
                  "field1"
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

### Expected Behaviour

Show which fields are required based on the **oneOf** rule, for example, in the Brazil case, all fields ("field1", "field2", and "field3") are required.

### Actual Behaviour

# Brazil Schema

```txt
https://julio.com/schemas/players/create#/properties/players/items/oneOf/0
```

| Abstract            | Extensible | Status         | Identifiable | Custom Properties | Additional Properties | Access Restrictions | Defined In                                                                               |
| :------------------ | :--------- | :------------- | :----------- | :---------------- | :-------------------- | :------------------ | :--------------------------------------------------------------------------------------- |
| Can be instantiated | No         | Unknown status | No           | Forbidden         | Allowed               | none                | [player_create.schema.json*](../../out/player_create.schema.json "open original schema") |

## 0 Type

`object` ([Brazil](player_create-properties-players-player-oneof-brazil.md))

# 0 Properties

| Property            | Type          | Required | Nullable       | Defined by                                                                                                                                                                                    |
| :------------------ | :------------ | :------- | :------------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [country](#country) | Not specified | Optional | cannot be null | [Player Creation](player_create-properties-players-player-oneof-brazil-properties-country.md "https://julio.com/schemas/players/create#/properties/players/items/oneOf/0/properties/country") |
| [legal](#legal)     | Not specified | Optional | cannot be null | [Player Creation](player_create-properties-players-player-oneof-brazil-properties-legal.md "https://julio.com/schemas/players/create#/properties/players/items/oneOf/0/properties/legal")     |

## country

`country`

*   is optional

*   Type: unknown

*   cannot be null

*   defined in: [Player Creation](player_create-properties-players-player-oneof-brazil-properties-country.md "https://julio.com/schemas/players/create#/properties/players/items/oneOf/0/properties/country")

### country Type

unknown

### country Constraints

**enum**: the value of this property must be equal to one of the following values:

| Value  | Explanation |
| :----- | :---------- |
| `"BR"` |             |

### country Examples

```json
"BR"
```

## legal

`legal`

*   is optional

*   Type: unknown

*   cannot be null

*   defined in: [Player Creation](player_create-properties-players-player-oneof-brazil-properties-legal.md "https://julio.com/schemas/players/create#/properties/players/items/oneOf/0/properties/legal")

### legal Type

unknown

___

**Comment by trieloff** [comment]
I don't think this is a real issue, as the `required` array is part of the `legal` property (where it has no effect) and not part of the surrounding `Brazil` schema.

**Comment by trieloff** [comment]
For conditional application of subschemas, you should probably use the `if`, `then`, `else` features introduced in draft-7 (https://json-schema.org/understanding-json-schema/reference/conditionals.html) although they are not yet supported in `jsonschema2md`: https://github.com/adobe/jsonschema2md/blob/main/schemasupport.md#a-vocabulary-for-applying-subschemas

**Comment by juliofalbo** [comment]
> I don't think this is a real issue, as the `required` array is part of the `legal` property (where it has no effect) and not part of the surrounding `Brazil` schema.

But the Brazil schema `required` is overriding the default rule, that's why this oneOf syntax exists.

**Comment by trieloff** [comment]
```
          {
            "title": "Brazil",
            "type": "object",
            "properties": {
              "country": {
                "examples": [
                  "BR"
                ],
                "testProperty": "BR",
                "enum": [
                  "BR"
                ]
              },
              "legal": {
                "required": [
                  "field1",
                  "field2",
                  "field3"
                ]
              }
            }
          }
```

This schema defines an object with a property `legal`. This property `legal` is an incomplete definition of an object. It defines `required` properties, but has no `properties` or `patternProperties` defined. If you want the `country` of the Player affect the schema of the `legal` object, you need to use the constructs I linked above.

I'd recommend you to create a couple of test files (valid and invalid) and then use a JSON Schema validator like `ajv` to ensure your schema does what you intend it to do. At the moment the schema and your verbal description of your expectations are not aligned.
