### ISSUE TITLE
Support a node API for this library

### ISSUE THREAD

**Issue by blake-mealey** [adobe/jsonschema2md#300]
### Feature request

Support a node API for this library. I would like to embed JSON schema markdown into another documentation generation tool but to do this I need a node API where I can give it the JSON schema object and it returns the markdown string.

Example:

```js
const jsonschema2md = require('@adobe/jsonschema2md')

const schema = { /* schema */ }
const markdown = jsonschema2md(schema, { /* options */ }})
```

I looked into your source briefly and determined I could import your lower-level files like `markdownBuilder.js` directly and reverse-engineer your `index.js` to get this working but at this point I gave up on it as I do not want to invest that much time into this at the moment.

There are other options which do have APIs like this but your project seems to be the highest quality and have the best spec support so I would appreciate it if you'd consider this feature.

**Comment by trieloff** [comment]
My gratitude goes out to @eduardomourar who implemented an API, modeled after the CLI for us.
