### ISSUE TITLE
Where does the example output live? 

### ISSUE THREAD

**Issue by jeffpatton1971** [adobe/jsonschema2md#311]
Trying to understand the -f parameter to the command. My assumption is that if I pass -f yaml i would get either a folder called examples, or yaml files included in the output folder or something. Additionally it's unclear how the tool would understand what examples would be, my assumption is that it may read in the default:{} property of a schema? the thought would be that it could generate an example based on the schema it was processing, but the question remains (if that's the case) where does this example output go?

**Comment by trieloff** [comment]
Examples are taken from two places:
- in a given schema add an `examples` array with example values as in this example: https://github.com/adobe/jsonschema2md/blob/1c9e14cbfcb26e0074d16f18c3da1ec163cdd722/examples/schemas/example.schema.json#L17
- if your schema is called `foo.schema.json`, put a file `foo.example.1.json` (any integer number works) next to it and it will get picked up as an example of the top level schema in the file. 

The output here https://github.com/adobe/jsonschema2md/blob/main/examples/docs/examples.md#examples-examples and here https://github.com/adobe/jsonschema2md/blob/main/examples/docs/examples.md#foo-examples will use the format specified with `-f`

**Comment by jeffpatton1971** [comment]
Lars,

Oh, that's cool! Thanks so much!


________________________________
