### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [adobe/jsonschema2md#33]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by trieloff** [comment]
Feel free to open a PR. So far we have not experienced too many issues with ejs, so this is not a top priority.

**Comment by Drulac** [comment]
Ok I will look to make a PR :-)

**Comment by trieloff** [comment]
Closing this for now, as it looks like we can deal with EJS's limitations quite well.
