### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by youneshenni** [adobe/jsonschema2md#331]
When I generate JSON schemas, I am unable to index them using git because the file names generated are too long, if my JSON file is very deep. Example filename: `docs/schemas/login-patternproperties-role-properties-login-extensions-extension-key-object-defining-the-extension-step-properties-extension-join-statements-items-properties-join-session-variables-patternproperties-a-z_.md`

Is there a way to fix this? Or does it need a PR?
I can do the PR if needed

**Comment by trieloff** [comment]
The easiest workaround is to give a `title` to the subschema that generates the long filename. `jsonschema2md` will use that over the complete path to generate a file name.

**Comment by trieloff** [comment]
Also, it seems that the file name length limitation exists only on windows and can be worked around by running

```
git config --system core.longpaths true
```

As the change to the file name pattern would be a breaking change, I'd keep things the way they are until this proves to be a more pervasive problem.

**Comment by youneshenni** [comment]
Thank you, I had fixed the problem with the solutions you had offered. So yes it's not that annoying of a problem.
Thanks for the library! Really appreciate it, very useful
