### ISSUE TITLE
Automatically provide enum's explanations

### ISSUE THREAD

**Issue by M-casado** [adobe/jsonschema2md#373]
### Expected Behaviour
A way to automatically add ``explanation`` to ``enum`` tables. In the example below (one of many ways to do this task), a way to associate the elements on the list given by the ``enum_explanation`` keyword to the elements in the ``enum`` keyword. 

### Actual Behaviour
Explanation for each element within ``enum`` tables is expected to be populated manually. 

#### Steps to Reproduce
Have test schema (``schema_test.json``) with enums:
```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "test_json",
    "type": "object",
    "title": "Test schema title",
    "description": "Test schema description",
    "properties": {
      "object1": {
        "type": "string",
        "title": "object1 Title",
        "description": "object1 description",
        "enum": ["enum1", "enum2"],
        "enum_explanation": ["enum1 explanation", "enum2_explanation"]
      }
    }      
  }
```
Generate markdown documents with ``jsonschema2md`` through the CLI:
```
jsonschema2md -d ./ -o ./markdown -e "json"
```
#### Platform and Version
* **Operating System**: Windows 10 with Windows Subsystem for Linux v2
* **node.js**: v16.13.0
* **jsonschema2md**: 6.1.4
#### Sample Code that illustrates the problem
Instead of having this output markdown:
| Value     | Explanation |
| :-------- | :---------- |
| `"enum1"` |             |
| `"enum2"` |             |

I would like to have:
| Value     | Explanation |
| :-------- | :---------- |
| `"enum1"` | enum1 explanation |
| `"enum2"` | enum2_explanation |

**Comment by trieloff** [comment]
You can use `meta:enum` instead. It is a map of enum value to description.

**Comment by M-casado** [comment]
Sorry to bother you again, @trieloff, but is there a place where one can find all used ``meta:...`` keywords? 

I could not find documentation about them or their reference at the "[detailed list of JSON Schema keywords supported by ``jsonschema2md``](https://github.com/adobe/jsonschema2md/blob/main/schemasupport.md)". I did find some within the code itself (``meta:status``, ``meta:extensible``, ``meta:license``...), but I am unsure of their usage and if there are others.

**Comment by trieloff** [comment]
The `meta:` keywords are mostly born out of the requirements of https://github.com/adobe/xdm you can find the closest thing to a reference here in the XDM meta schema: https://github.com/adobe/xdm/blob/master/meta.schema.json
