### ISSUE TITLE
Allow alternative extensions

### ISSUE THREAD

**Issue by autarch** [adobe/jsonschema2md#43]
It would be really nice to allow other extensions besides `.schema.json`. This is not at all standard, and AFAICT the most common recommendation is to simply use `.json`. It'd be nice if this was an option on the CLI.

**Comment by trieloff** [comment]
I agree. We use `*.schema.json`, so that we can automatically merge `*.example.*.json` and `*.description.md`, which makes authoring a bit easier, but it would be a nice addition to support other extensions.

**Comment by anjankaur** [comment]
Currently, schema and example files are in same folder. And so we identify these with their respective extensions. If we support just `.json` then, we won't be able to differentiate between them without actually first parsing the files.  
Maybe what we can do is, if a file does not fit into these 2 extensions, and has `.json` extension then automatically consider it as schema file. Or we can decide to put examples in separate folder(less desirable option, for me).

**Comment by trieloff** [comment]
I would add three parameters: `--schema-extension` and `--example-extension` and maybe `--description-extension` to clarify this.

**Comment by anjankaur** [comment]
Yeah this is a good idea. But this would necessarily mandate that both extensions should be different, using `.json` for both won't work.

**Comment by robinvenneman** [comment]
I am looking into this tool use it for schema's in a certain folder with plain `.json` extensions... so it would be nice to be able to configure that. Also wondering why the output always contains the validated json files as well, might be interesting to make that optional.

**Comment by trieloff** [comment]
@robinvenneman one reason why we create the JSON Schema file output is to allow inlining of `*.description.md` files, so that authoring longer descriptions becomes a bit easier.

In the future, we might even support `js` input format, so that authoring schemas becomes a bit less verbose.

But I agree on making it optional.

**Comment by robinvenneman** [comment]
Alright, I've added a CLI option in [`
3d25c37`](https://github.com/robinvenneman/jsonschema2md/commit/3d25c37bee9adc987032ddd5903250eeab302a09). @trieloff feedback welcome... please let me know if you can use this and if it requires additional work for a PR.

**Comment by trieloff** [comment]
Looks good. What would make it really fast for me to merge:

- add a test case that fails and commit (CircleCI will mark it)
- fix the test case

**Comment by robinvenneman** [comment]
@trieloff I've added a test which should fail at the moment in [feature/43-schema-extensions](https://github.com/robinvenneman/jsonschema2md/tree/feature/43-schema-extensions).
Perhaps a schema with a different file extension can be added to test this flag.
