### ISSUE TITLE
The generator does not handle allOf/anyOf/oneOf properly if schemas include properties, and are not references.

### ISSUE THREAD

**Issue by MaxSavenkov** [adobe/jsonschema2md#52]
This schema:

```json
{
  "$id" : "id",
  "title" : "title",
  "description" : "desc", 
  "type" : "object",

  "allOf": [
    { "properties": {
        "type": { "enum": [ "one", "two" ] }
      }, "required" : ["type"]
    },
    { "properties": {
        "test": { "type": "string" }
      }, "required" : ["test"]
    }
  ]
}
```
Produces this MarkDown:
```markdown
# title Schema

```
id
```

desc

| Abstract | Extensible | Status | Custom Properties | Additional Properties | Defined In |
|----------|------------|--------|-------------------|-----------------------|------------|
| Can be instantiated | No | Experimental | Forbidden | Permitted | [protocol2.schema.json](protocol2.schema.json) |

# title Properties

| Property | Type | Required | Defined by |
|----------|------|----------|------------|
| [test](#test) | `string` | **Required** | title (this schema) |
| `*` | any | Additional | this schema *allows* additional properties |

## test


`test`
* is **required**
* type: `string`
* defined in this schema

### test Type


`string`
```

The "type" property disappears completely. However, this is a valid schema that requires both properties. Additionally, if you change one of the "allOf" elements to "$ref" with the same content, everything works just fine. 

The same problem applies to anyOf and oneOf combinations.

**Comment by MaxSavenkov** [comment]
Is there any difference between the three in terms of output? "and", "or" and "xor" examples from https://github.com/adobe/jsonschema2md/blob/master/examples/docs/complex.schema.md seem to follow the same rules visually, with just a different preface and headers.

**Comment by trieloff** [comment]
The difference is that in `complex.schema.json` we have the `oneOf` at the level of individual properties, not at the root of the schema.

One way to express it could be a big preface with multiple property tables – and then a repetition of the property lists.
