### ISSUE TITLE
Optional JSON schema output

### ISSUE THREAD

**Issue by robinv85** [adobe/jsonschema2md#57]
As mentioned in [#43](https://github.com/adobe/jsonschema2md/issues/43) it would be nice to make the output of JSON schema's optional (which implies no output by default) or at least configurable. 

I think it would be easiest to implement by making it optional, so if the `-x path/to/schema-output` flag is not set, there would be no output, this doesn't require additional CLI arguments but it's a bit of a breaking change compared to previous versions...

**Comment by trieloff** [comment]
I’ve been thinking about suppressing schema output using `-x -` which wouldn’t be a breaking change, but also wouldn’t introduce a new CLI parameter.

**Comment by robinvenneman** [comment]
Ok, so how would that work? I have made it optional in [23faa53](https://github.com/robinvenneman/jsonschema2md/commit/23faa5339c7b34ab93d1b8df997f8edb2f046695) which I can use right now to avoid having to delete the files afterwards...

**Comment by trieloff** [comment]
Change the condition in `cli.js` to check for equality with `-`, the rest looks ok. Maybe use `null` instead of an empty string, although JS things they are the same anyway.

**Comment by robinvenneman** [comment]
Alright, yeah I had first used `null` but the JS Doc has a type `string` so I thought it made more sense to default to empty string which is indeed also falsy in the `if()` condition... might be more safe with strict equality check though, updating with the `-` to suppress the output.

**Comment by robinvenneman** [comment]
Ok so I've changed it in [feature/57-suppress-schema-output](https://github.com/robinvenneman/jsonschema2md/tree/feature/57-suppress-schema-output) to suppress wit the `-x -` flag, still kept empty string but used strict equality check, should probably also add a unit test?

**Comment by trieloff** [comment]
Unit tests are always appreciated.

**Comment by trieloff** [comment]
@robinvenneman do you want to open a PR for your work in progress? I'm happy to add the remaining tests.

**Comment by robinvenneman** [comment]
@trieloff Alright, didn't find the time yet to add a test, I'll open a PR.
