### ISSUE TITLE
Hello from JSON Schema Team!

### ISSUE THREAD

**Issue by benjagm** [adobe/jsonschema2md#591]
Hi everyone!

This is Benjamin from the JSON Schema Team. We'd like to congratulate everyone for this great tool! We are so excited every time we found cool JSON Schema tooling like this. We'd like to check with you if you will be open to get jsonschema2md added to the JSON Schema tooling page: https://json-schema.org/implementations

The process is so simple and as a result to get the project added we'll better serve the community providing more tools for more use cases and hopefully this will increase adoption and contributions to your project.

Please let me know what you think.

**Comment by trieloff** [comment]
Hi Benjamin, yes, we'd be open to that.
