### ISSUE TITLE
Link to Json schema(.json) does not work in header table(DefinedIn column)

### ISSUE THREAD

**Issue by anjankaur** [adobe/jsonschema2md#64]
## What did you do
Click on the .json link for the schema in  DefinedIn column
## What did you expect to happen
Open correct .json file of the schema
## What happened
Error 404(Incorrect link)

## Do you have example files:
This is for all .md files actually but examples below
In Examples: https://github.com/adobe/jsonschema2md/blob/master/examples/docs/arrays.schema.md
In XDM: https://github.com/adobe/xdm/blob/master/docs/reference/assets/aggregated-asset.schema.md

**Comment by pulse14** [comment]
I have the same problem

**Comment by rbuckland** [comment]
I have tracked it this far .. 
* The MD link is created from this file - [templates/md/innerSchema.ejs](https://github.com/adobe/jsonschema2md/blob/master/templates/md/innerSchema.ejs)
 It is using a pre-loaded context object (per schema) file etc, called `$oSchema` with a key called `$oSchema.$linkPath` 
* This `$oSchema.$linkPath` seems to be set only in the file [lib/schema.js](https://github.com/adobe/jsonschema2md/blob/master/lib/schema.js)

But that is far as I can go - it needs some beastly context mapped in your brain to see what on earth is going on. 

(why don't people comment code anymore :-( )
