### ISSUE TITLE
Draft support not stated

### ISSUE THREAD

**Issue by Relequestual** [adobe/jsonschema2md#79]
## What did you do
I visited this repo on github.

## What did you expect to happen
I expect to see which draft/s of JSON Schema are supported.

## What happened
I could not find which draft/s of JSON Schema are supported.

## What's your environment
A browser.

**Comment by trieloff** [comment]
jsonschema2md was built with the version of JSON Schema that [XDM](https://github.com/adobe/xdm) is using in mind. That would be draft-06. However, we don't support all of it, so I'm not sure if we should claim draft-06 compatibility.

**Comment by Relequestual** [comment]
OK. You could consider documenting the subset of features from draft-6 you DO support, and noting the keywords you DO NOT support. That seems to be the usual pattern.
