### ISSUE TITLE
Unable To Generate Markdown and Logs are Unclear

### ISSUE THREAD

**Issue by thefringeninja** [adobe/jsonschema2md#83]
## What did you do

Attempt to generate docs from schema via yarn

## What did you expect to happen

Markdown

## What happened

```
yarn jsonschema2md -d StreamMetadata/Schema/SetStreamMetadata.schema.json
yarn run v1.10.1
warning package.json: No license field
$ /mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/.bin/jsonschema2md -d StreamMetadata/Schema/SetStreamMetadata.schema.json
07
[winston] Attempt to write logs with no transports {"level":"info","message":"output directory: %s"}
[winston] Attempt to write logs with no transports {"level":"error"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## What's your environment

* Operating System: Ubuntu bionic running on WSL
* node.js version: v8.10.0
* yarn version: v1.10.1
* jsonschema2md version: 1.1.0
## Do you have example files:

For this schema
```json
{
  "title": "Set Stream Metadata",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/hyper-schema#",
  "properties": {
    "maxCount": {
      "type": "integer",
      "minimum": 1
    },
    "maxAge": {
      "type": "integer",
      "minimum": 1
    },
    "metadataJson": {
      "type": "object",
      "x-schema-form": {
        "key": "metadataJson",
        "type": "textarea",
        "rows": 30
      }
    }
  }
}
```

I have validated this schema against `http://json-schema.org/draft-07/schema#` here: https://www.jsonschemavalidator.net/. Unfortunately it looks like the real error message is being hidden by a logging error.

**Comment by thefringeninja** [comment]
Tried that, it didn't work :( Same result if I force the schema with `-v 07`

**Comment by trieloff** [comment]
Can you leave out the `-d StreamMetadata/Schema/SetStreamMetadata.schema.json
07` parameter? I ran it without it (because I don't have the file)

**Comment by thefringeninja** [comment]
Hey thanks for the quick reply! running it with no args gives
```
Missing required arguments: d
```
Just so you know I have also tried downgrading to 1.0.6. Since that doesn't support 07 of the schema I also changed `$schema` to `http://json-schema.org/draft-06/schema#`. https://www.jsonschemavalidator.net/ says the schema is ok. Still fails but at least I get a stack trace!
```
info: output directory: /mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/out
error:  message=Unexpected token ﻿ in JSON at position 0, stack=SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at fs.readFileAsync.then.data (/mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/@adobe/jsonschema2md/lib/readSchemaFile.js:26:25)
    at tryCatcher (/mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/bluebird/js/release/promise.js:638:18)
    at /mnt/c/dev/SQLStreamStore.HAL/src/SqlStreamStore.HAL/node_modules/bluebird/js/release/nodeback.js:42:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
error Command failed with exit code 1.
```
Changing `-d` to the actual file name yields the same error. Changing it to a non existing file says the file doesn't exist. 

(You can tell I'm debugging this as I'm writing the issue)

Removed the byte order mark from the file and it worked. Woooo! After that I upgraded again to 1.1.0 and changed the schema back to 07. That worked too. Still doesn't work with hyper-schema but I can live with that for now.

**Comment by trieloff** [comment]
Glad to hear that. 

It looks like the BOM is invalid JSON anyway: https://tools.ietf.org/html/rfc7159#section-8.1 – but that also explains why the copy & pasted JSON schema validates.

I'm keeping the issue open so that we can fix the logger implementation.
