### ISSUE TITLE
Dependency circular-json@0.3.3 deprecated

### ISSUE THREAD

**Issue by claybridges** [adobe/jsonschema2md#96]
After running `$ npm install` in the repo, I get this:
```
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```
Sound like an update to `flatted` is the fix. https://github.com/WebReflection/flatted

**Comment by trieloff** [comment]
Let's wait for the dependency that introduced it to update it, then greenkeeper will take care of it.
